version: "3.9"

services:
  air:
    container_name: tasqcoin-backend
    image: cosmtrek/air
    working_dir: /app
    environment:
      - LOAD_ENV_FILE=true
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  app:
    container_name: tasqcoin-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LOAD_ENV_FILE=true
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    volumes:
      - ./.env:./.env
    links:
      - "db"
    depends_on:
      - db

  db:
    image: postgres
    container_name: db_tasqcoin
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
